[2024-08-24 16:05:31] DEBUG - matplotlib - matplotlib data path: C:\Users\Nikolas Sanderson\Documents\GitHub\Python-Visual\noaa-ocean-challenge\.venv\lib\site-packages\matplotlib\mpl-data
[2024-08-24 16:05:31] DEBUG - matplotlib - CONFIGDIR=C:\Users\Nikolas Sanderson\.matplotlib
[2024-08-24 16:05:31] DEBUG - matplotlib - interactive is False
[2024-08-24 16:05:31] DEBUG - matplotlib - platform is win32
[2024-08-24 16:05:31] DEBUG - matplotlib - CACHEDIR=C:\Users\Nikolas Sanderson\.matplotlib
[2024-08-24 16:05:31] DEBUG - matplotlib.font_manager - Using fontManager instance from C:\Users\Nikolas Sanderson\.matplotlib\fontlist-v390.json
[2024-08-24 16:05:37] ERROR - super_gradients.training.sg_trainer.sg_trainer - Uncaught exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\Nikolas Sanderson\Documents\GitHub\Python-Visual\noaa-ocean-challenge\test.py", line 142, in <module>
    trainer.train(
  File "C:\Users\Nikolas Sanderson\Documents\GitHub\Python-Visual\noaa-ocean-challenge\.venv\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 1480, in train
    first_train_batch = next(iter(self.train_loader))
  File "C:\Users\Nikolas Sanderson\Documents\GitHub\Python-Visual\noaa-ocean-challenge\.venv\lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
  File "C:\Users\Nikolas Sanderson\Documents\GitHub\Python-Visual\noaa-ocean-challenge\.venv\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Nikolas Sanderson\Documents\GitHub\Python-Visual\noaa-ocean-challenge\.venv\lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Nikolas Sanderson\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
